version: '3.5'

networks:
  mysql:
    driver: bridge
  backend:
    driver: bridge
  frontend:
    driver: bridge

services:
  mysql:
    image: mysql
    build: ./mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mysql
    volumes:
      - ${DATA_DIR}/mysql:/var/lib/mysql
    networks:
      - mysql

  nats:
    image: nats:2.6.6
    ports:
      - ${NATS_CLIENT}:4222
      - ${NATS_CLLUSTER}:6222
      - ${NATS_HTTP}:8222
    networks:
      - backend
    container_name: nats
  
  nats-service:
    build:
      context: ./
      dockerfile: nats/Dockerfile
    ports:
      - ${NATS_PORT}:${NATS_PORT}
    environment:
      NATS_URI: "nats://nats:4222"
    container_name: nats-service
    networks:
      - backend
      - mysql
    depends_on:
      - nats

  auth-service:
    build: 
      context: ./
      dockerfile: auth/Dockerfile
    ports:
      - 3001:3001
    container_name: auth-service
    networks:
      - backend
      - mysql
    depends_on:
      - nats
      - mysql
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SESSION_TIME: ${SESSION_TIME}
      JWT_AUD: ${JWT_AUD}
      JWT_ISS: ${JWT_ISS}
      NATS_URI: "nats://nats:4222"
      MYSQL_HOST: "mysql:3306"
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      AUTH_PORT: ${AUTH_PORT}

  todo-service:
    build: 
      context: ./
      dockerfile: todo/Dockerfile
    ports:
      - 3002:3002
    container_name: todo-service
    networks:
      - backend
      - mysql
    depends_on:
      - nats
      - mysql
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SESSION_TIME: ${SESSION_TIME}
      JWT_AUD: ${JWT_AUD}
      JWT_ISS: ${JWT_ISS}
      NATS_URI: "nats://nats:4222"
      MYSQL_HOST: "mysql:3306"
      MYSQL_ROOT_USERNAME: ${MYSQL_ROOT_USERNAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TODO_PORT: ${TODO_PORT}
      
  next-todo:
    build:
      context: ./
      dockerfile: next-todo-tailwind/Dockerfile
    ports:
      - ${NEXT_PORT}:${NEXT_PORT}
    container_name: next-todo
    volumes:
      - ./next-todo-tailwind:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    networks:
      - frontend
    