version: '3.5'

networks:
  backend:
    driver: bridge

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    hostname: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    container_name: mysql
    networks:
      - backend

  nats:
    image: nats:2.6.6
    ports:
      - 4222:4222
      - 6222:6222
      - 8222:8222
    networks:
      - backend
    container_name: nats
  
  nats-service:
    build:
      context: ./
      dockerfile: nats/Dockerfile
    ports:
      - 8181:8181
    environment:
      NATS_URI: "nats://nats:4222"
    container_name: nats-service
    networks:
      - backend
    depends_on:
      - nats

  auth-service:
    build: 
      context: ./
      dockerfile: auth/Dockerfile
    ports:
      - 3001:3001
    container_name: auth-service
    networks:
      - backend
    depends_on:
      - nats
    environment:
      SECRET_KEY: "ezioauditore"
      SESSION_TIME: "15"
      JWT_AUD: "go-todo.jwtgo"
      JWT_ISS: "jwtgo.io"
      NATS_URI: "nats://nats:4222"
      AUTH_PORT: "3001"
      MYSQL_HOST: "mysql:3306"
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"

  todo-service:
    build: 
      context: ./
      dockerfile: todo/Dockerfile
    ports:
      - 3002:3002
    container_name: todo-service
    networks:
      - backend
    depends_on:
      - nats
    environment:
      SECRET_KEY: "ezioauditore"
      SESSION_TIME: "15"
      JWT_AUD: "go-todo.jwtgo"
      JWT_ISS: "jwtgo.io"
      NATS_URI: "nats://nats:4222"
      TODO_PORT: "3002"
      MYSQL_HOST: "mysql:3306"
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "root"